include=~/.cache/wal/colors-fuzzel.ini

[main]
font=Fira Code:size=14
prompt="> "
icon-theme=hicolor
icons-enabled=no
fields=name,generic,comment,categories,filename,keywords
# Terminal-like width
width=50
lines=12
horizontal-pad=20
vertical-pad=10
inner-pad=5

# Make it a solid overlay
layer=overlay

[colors]
# Format: RRGGBBAA (Last two digits 'ff' = 100% Opaque)
background=000000ff
text=ffffffff
match=db0000ff
selection=db0000
selection-text=000000ff
; border=db0000ff

[border]
width=2
radius=0  # Sharp corners (Suckless style)
